FROM node:20

RUN apt-get update && \
    apt-get install -y \
        git \
        git-annex \
        rsync \
        openssh-client \
        ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app