name: Preview Deploy

on:
  push:
    branches:
    - "**"
#rebuild
jobs:
  deploy-preview:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy preview environment
        run: |
          chmod +x scripts/deploy-preview.sh
          ./scripts/deploy-preview.sh "${{ github.ref_name }}"